### ISSUE TITLE
Log IN

### ISSUE THREAD

**Issue by ryanG394** [Alex91700/gpi-projet#18]
Pour l'instant on ne peut pas passer par le logIn, obligation de passer par référentiel.
Trouver une solution pour s'enregistrer correctement.

**Comment by b-henriques** [comment]
le nouveau commit devra corriger ce problème. Il est maintenant possible de faire logIn et logOut correctement. Lors du logIn l'utilisateur est redirigé vers la section du site que lui correspond (administrateur de référentiel vers administration du référentiel par exemple)
