### ISSUE TITLE
erreur suppression d'article et référentiel individus

### ISSUE THREAD

**Issue by ZeineId** [Alex91700/gpi-projet#26]
erreur lorsqu'on souhaite supprimer un article dans la section Administration du référentiel -> Vue ensemble referentiel_articles

impossible d'accéder a la vue d'ensemble du référentiel des individus

**Comment by b-henriques** [comment]
cet erreur a déjà été corrigé, t'as testé l'application sur un ancien commit
=> faut pas oublie de faire un merge (pullrequest) avant de commencer les nouveaux tests
